INSERT INTO students (forename, surname, birth_year) VALUES("Kathy", "Beckmann", "2002-06-18");
INSERT INTO students (forename, surname, birth_year) VALUES("Theobald", "Heydrich", "2005-08-11");
INSERT INTO students (forename, surname, birth_year) VALUES("Bernd", "Dietz", "2005-06-22");
INSERT INTO students (forename, surname, birth_year) VALUES("Emilie", "Pölitz", "2002-12-04");
INSERT INTO students (forename, surname, birth_year) VALUES("Bekir", "Dehmel-Bolzmann", "2002-05-08");
INSERT INTO students (forename, surname, birth_year) VALUES("Kevin", "Schmidt", "2003-03-17");
INSERT INTO students (forename, surname, birth_year) VALUES("Oxana", "Eberth", "2002-01-01");
INSERT INTO students (forename, surname, birth_year) VALUES("Viola", "Franke", "2002-07-02");
INSERT INTO students (forename, surname, birth_year) VALUES("Michaela", "Schottin", "2003-10-23");
INSERT INTO students (forename, surname, birth_year) VALUES("Karen", "Benthin", "2002-06-08");
INSERT INTO students (forename, surname, birth_year) VALUES("Cäcilie", "Bonbach", "2002-02-13");
INSERT INTO students (forename, surname, birth_year) VALUES("Frau", "Anny Scheel", "2003-01-19");
INSERT INTO students (forename, surname, birth_year) VALUES("Miroslaw", "Bolzmann", "2002-09-25");
INSERT INTO students (forename, surname, birth_year) VALUES("Falk", "Henk", "2002-07-08");
INSERT INTO students (forename, surname, birth_year) VALUES("Heini", "Scholl", "2004-01-03");
INSERT INTO students (forename, surname, birth_year) VALUES("Thomas", "Scholz", "2005-06-19");
INSERT INTO students (forename, surname, birth_year) VALUES("Wolf", "Dieter Gehringer", "2004-04-12");
INSERT INTO students (forename, surname, birth_year) VALUES("Hubert", "Franke", "2002-07-15");
INSERT INTO students (forename, surname, birth_year) VALUES("Iwan", "Schweitzer", "2005-04-26");
INSERT INTO students (forename, surname, birth_year) VALUES("Mara", "Pruschke", "2003-04-12");